# Generated by Django 3.1.1 on 2020-09-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200922_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluations',
            name='description',
            field=models.TextField(verbose_name='Опсание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/photos_products/%Y/%m/%d', verbose_name='Иконка'),
        ),
        migrations.CreateModel(
            name='ImageProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='photos/photos_products/%Y/%m/%d', verbose_name='Фотография')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': 'Фотографии товаров',
            },
        ),
    ]
