# Generated by Django 3.1.1 on 2020-09-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_textsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textsite',
            options={'ordering': ['header'], 'verbose_name': 'Текста на сайта', 'verbose_name_plural': 'Текст на сайте'},
        ),
        migrations.AddField(
            model_name='imageproducts',
            name='photosmin',
            field=models.ImageField(blank=True, null=True, upload_to='photos/photos_products/%Y/%m/%d', verbose_name='Мини фотография'),
        ),
    ]
