# Generated by Django 3.1.1 on 2020-09-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200923_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='execution_technique',
        ),
        migrations.RemoveField(
            model_name='products',
            name='material',
        ),
        migrations.AlterField(
            model_name='imageproducts',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products', verbose_name='Товар'),
        ),
    ]
